import JSZip from 'jszip';

import { printPreset } from '@/generator';
import { printDeployScript } from '@/generator/aave/deployScript';
import {
  assembleAttackTests,
  type AttackSnippetFile,
} from '@/generator/attacks/assembleAttackTests';
import { EVM_VERSION, REMAPPINGS, SOLC_VERSION, type GenerateOptions } from '@/types';

/**
 * A9 — a Foundry project the user can actually run, and a Remix link that needs no
 * infrastructure at all.
 *
 * `zipFoundry` from @openzeppelin/wizard is not usable here: the published package
 * requires '../openzeppelin-contracts', which it does not ship. This follows the
 * shape of its source instead.
 */

/**
 * The demo environment's PUBLIC RPC. It serves archive state at FORK_BLOCK, which a
 * free public endpoint will not. Deliberately not the Admin RPC — that one carries
 * tenderly_setBalance and friends and must never reach a downloadable file.
 */
const DEMO_RPC =
  'https://virtual.mainnet.eu.rpc.tenderly.co/petnica2026/project/harness-mainnet-1786200683168';
const FORK_BLOCK = '25710954';

const FOUNDRY_TOML = `[profile.default]
src = "src"
test = "test"
script = "script"
libs = ["lib"]
solc = "${SOLC_VERSION}"
evm_version = "${EVM_VERSION}"
optimizer = true
optimizer_runs = 200

# The attack suite forks real mainnet. Point MAINNET_RPC_URL at any archive-capable
# endpoint, or at the Tenderly Virtual Environment's public RPC.
[rpc_endpoints]
mainnet = "\${MAINNET_RPC_URL}"
`;

/**
 * The `forge install` lines, chosen by preset.
 *
 * This was a flat constant naming the two Aave repos. Once the Morpho preset
 * shipped, an exported Morpho project carried a remappings.txt pointing at
 * lib/morpho-blue and a setup.sh that never created it — so the download failed
 * on its first `forge test`, which is the one outcome this file exists to
 * prevent. Deriving the list from the preset makes that mismatch impossible.
 */
function setupSh(preset: GenerateOptions['preset']): string {
  const deps: [string, string][] =
    preset === 'morpho-blue-vault'
      ? [
          ['foundry-rs/forge-std', 'lib/forge-std'],
          ['OpenZeppelin/openzeppelin-contracts', 'lib/openzeppelin-contracts'],
          ['morpho-org/morpho-blue', 'lib/morpho-blue'],
        ]
      : [
          ['foundry-rs/forge-std', 'lib/forge-std'],
          ['OpenZeppelin/openzeppelin-contracts', 'lib/openzeppelin-contracts'],
          ['aave/aave-v3-core', 'lib/aave-v3-core'],
          ['aave/aave-v3-periphery', 'lib/aave-v3-periphery'],
        ];

  const width = Math.max(...deps.map(([repo]) => repo.length));
  const installs = deps
    .map(([repo, path]) => {
      const pad = ' '.repeat(width - repo.length);
      return `forge install ${repo} --no-git --quiet${pad}  # -> ${path}`;
    })
    .join('\n');

  return `#!/usr/bin/env bash
set -euo pipefail

# Generated by HARNESS. Installs the dependencies the generated code imports.
# The install paths below are what remappings.txt expects — changing one means
# changing the other.
${installs}

echo
echo "Now set MAINNET_RPC_URL and run:  forge test -vv"
`;
}

const ENV_EXAMPLE = `# The HARNESS demo Tenderly Virtual Environment (public RPC, read-only: it rejects
# admin cheatcodes). Swap it for your own endpoint for anything beyond a trial run.
#
# IMPORTANT: this must be an ARCHIVE-capable endpoint if TENDERLY_FORK_BLOCK is set.
# Free public RPCs prune old state and answer 403 "Archive requests require a
# personal token" once the pinned block is more than ~128 blocks behind head.
MAINNET_RPC_URL=${DEMO_RPC}

# Pinned so the suite is reproducible: an unpinned fork drifts with mainnet, and a
# suite that is green today goes red tomorrow for reasons unrelated to the code.
# Comment this out to fork at latest, which works on any RPC including free ones.
TENDERLY_FORK_BLOCK=${FORK_BLOCK}

# Only needed for script/*.s.sol broadcasts.
PRIVATE_KEY=
`;

function readme(opts: GenerateOptions, testNames: string[], findingIds: string[]): string {
  return `# ${opts.name}

Generated by [HARNESS](https://harness-web-livid.vercel.app) — the wizard that ships
the attacks on the code it writes.

## What this is

An Aave v3 integration contract, hardened against ${findingIds.length} documented findings,
plus a Foundry suite that attacks it on a fork of real mainnet.

| File | |
|---|---|
| \`src/${opts.name}.sol\` | the contract |
| \`test/${opts.name}.attack.t.sol\` | ${testNames.length} attack tests, each citing a real incident |
| \`script/${opts.name}.s.sol\` | deploy script |

## Run it

\`\`\`bash
./setup.sh
cp .env.example .env    # set MAINNET_RPC_URL
forge test -vv
\`\`\`

The tests fork mainnet and run against the live Aave Pool, resolved through the
PoolAddressesProvider rather than hardcoded.

## The tests

${testNames.map((t) => `- \`${t}\``).join('\n')}

## Findings mitigated

${findingIds.map((f) => `- \`${f}\``).join('\n')}

## Prove they mean something

Delete a mitigation and re-run — the corresponding test should fail. If it does not,
the test is decoration. For example, removing the \`initiator != address(this)\` check
from a flash-loan receiver should turn \`test_RejectsThirdPartyInitiator\` red.

## Attribution

Findings are mapped to the [evm-hack-registry](https://github.com/sanbir/evm-hack-registry)
and [DeFiHackLabs](https://github.com/SunWeb3Sec/DeFiHackLabs) corpora, tagged with the
[AuditVault](https://github.com/AuditWare/AuditVault) taxonomy. Built on
[OpenZeppelin Contracts](https://github.com/OpenZeppelin/openzeppelin-contracts).

This generated code is MIT. HARNESS itself is AGPL-3.0.
`;
}

export async function buildProjectZip(
  opts: GenerateOptions,
  snippets: AttackSnippetFile,
  findingIds: string[],
): Promise<Blob> {
  const { source: tests, testNames } = assembleAttackTests(opts, snippets);

  const zip = new JSZip();
  zip.file(`src/${opts.name}.sol`, printPreset(opts));
  zip.file(`test/${opts.name}.attack.t.sol`, tests);
  zip.file(`script/${opts.name}.s.sol`, printDeployScript(opts));
  zip.file('foundry.toml', FOUNDRY_TOML);
  zip.file('remappings.txt', REMAPPINGS.join('\n') + '\n');
  zip.file('.env.example', ENV_EXAMPLE);
  zip.file('setup.sh', setupSh(opts.preset), { unixPermissions: '755' });
  zip.file('README.md', readme(opts, testNames, findingIds));

  return zip.generateAsync({ type: 'blob' });
}

/**
 * Remix reads the contract straight out of the URL fragment. Mechanism per OZ's
 * own `ui/src/solidity/remix.ts`: base64 of the UTF-8 bytes, padding stripped.
 */
export function remixUrl(source: string): string {
  const bytes = new TextEncoder().encode(source);
  let binary = '';
  for (const b of bytes) binary += String.fromCharCode(b);
  const code = btoa(binary).replace(/=*$/, '');

  const remaps = btoa(REMAPPINGS.join('\n')).replace(/=*$/, '');
  return (
    `https://remix.ethereum.org/#code=${code}` +
    `&remaps=${remaps}` +
    `&activate=solidity,solidityUnitTesting` +
    `&autoCompile=true` +
    `&version=soljson-v${SOLC_VERSION}+commit.40a35a09`
  );
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
