import { buildFlashLoanReceiver } from '@/generator/aave/flashLoanReceiver';
import {
  CONTRACT_NAME_RE,
  IMPORT_PATHS,
  SOLIDITY_PRAGMA,
  type FindingId,
  type GenerateOptions,
} from '@/types';

/**
 * Attack-test assembler (task A5).
 *
 * Takes Agent B's `fixtures/attack-snippets.json`, keeps only the snippets whose
 * finding ID the generated contract actually mitigates, substitutes placeholders,
 * and emits a Foundry fork test.
 *
 * The snippets are authored against the hardened contract, so a passing suite is
 * evidence the mitigations hold — not evidence the tests were written to pass.
 */

export interface AttackSnippet {
  testName: string;
  title: string;
  incidents: { name: string; url: string; pocFolder?: string }[];
  comments?: string[];
  body: string[];
  helpers?: string[];
}

export interface AttackSnippetFile {
  schemaVersion: string;
  snippets: Record<string, AttackSnippet>;
}

/** Aave v3 Ethereum mainnet, from @bgd-labs/aave-address-book. */
export const MAINNET = {
  POOL_ADDRESSES_PROVIDER: '0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e',
  REWARDS_CONTROLLER: '0x8164Cc65827dcFe994AB23944CBC90e0aa80bFcb',
  USDC: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
  aUSDC: '0x98C23E9d8f34FEFb1B7BD6a91B7FF122F4e16F5c',
} as const;

const INSTANCE = 'harness';

/**
 * Maps a constructor argument name from the generated contract onto the expression
 * the test should pass. Reading the names off the ContractBuilder rather than
 * re-deriving them means the test cannot drift from the contract it deploys.
 */
const CONSTRUCTOR_BINDINGS: Record<string, string> = {
  addressesProvider: 'address(PROVIDER)',
  asset_: 'ASSET',
  initialOwner: 'owner',
  defaultAdmin: 'owner',
  operator: 'owner',
  rewardsController: 'REWARDS_CONTROLLER',
};

export function assembleAttackTests(
  opts: GenerateOptions,
  file: AttackSnippetFile,
): { source: string; testNames: string[]; skipped: FindingId[] } {
  if (!CONTRACT_NAME_RE.test(opts.name)) {
    throw new Error(`Refusing to interpolate an invalid contract name: ${opts.name}`);
  }

  const { contract, appliedFindingIds } = buildFlashLoanReceiver(opts);
  const applied = new Set<string>(appliedFindingIds);

  const chosen: [FindingId, AttackSnippet][] = [];
  const skipped: FindingId[] = [];
  for (const [id, snippet] of Object.entries(file.snippets)) {
    if (applied.has(id)) chosen.push([id as FindingId, snippet]);
    else skipped.push(id as FindingId);
  }

  const subs: Record<string, string> = {
    '{{CONTRACT}}': INSTANCE,
    '{{CONTRACT_TYPE}}': opts.name,
    '{{POOL}}': 'POOL',
    '{{ASSET}}': 'ASSET',
    '{{ATOKEN}}': 'ATOKEN',
    '{{PARAMS}}': '_defaultParams()',
    '{{PARAMS_STRUCT}}': '_defaultFlashParams()',
    '{{OWNER}}': 'owner',
  };

  const ctorArgs = contract.constructorArgs.map((a) => {
    const bound = CONSTRUCTOR_BINDINGS[a.name];
    if (!bound) throw new Error(`No test binding for constructor argument '${a.name}'`);
    return bound;
  });

  const lines: string[] = [
    '// SPDX-License-Identifier: MIT',
    `pragma solidity ${SOLIDITY_PRAGMA};`,
    '',
    `import {Test} from "${IMPORT_PATHS.FORGE_TEST}";`,
    `import {IPool} from "${IMPORT_PATHS.POOL}";`,
    `import {IPoolAddressesProvider} from "${IMPORT_PATHS.POOL_ADDRESSES_PROVIDER}";`,
    `import {IERC20} from "${IMPORT_PATHS.IERC20}";`,
    `import {${opts.name}} from "../src/${opts.name}.sol";`,
    '',
    `/// @title ${opts.name}AttackTest`,
    '/// @notice Generated by HARNESS. Every test below is derived from a documented',
    '/// @notice incident, cited in the comment above it. These run against real Aave',
    '/// @notice on a mainnet fork — not against a mock.',
    `contract ${opts.name}AttackTest is Test {`,
    `    IPoolAddressesProvider internal constant PROVIDER =`,
    `        IPoolAddressesProvider(${MAINNET.POOL_ADDRESSES_PROVIDER});`,
    `    address internal constant ASSET = ${opts.asset ?? MAINNET.USDC};`,
    `    address internal constant ATOKEN = ${MAINNET.aUSDC};`,
  ];

  if (opts.claimRewards) {
    lines.push(`    address internal constant REWARDS_CONTROLLER = ${MAINNET.REWARDS_CONTROLLER};`);
  }

  lines.push(
    '',
    '    IPool internal POOL;',
    `    ${opts.name} internal ${INSTANCE};`,
    '    address internal owner;',
    '',
    '    function setUp() public {',
    '        // No fork block is pinned yet: the Tenderly Virtual Environment forks at',
    '        // latest until TENDERLY_FORK_BLOCK is published. Setting that env var pins',
    '        // both sides without regenerating anything.',
    '        uint256 forkBlock = vm.envOr("TENDERLY_FORK_BLOCK", uint256(0));',
    '        if (forkBlock == 0) {',
    '            vm.createSelectFork(vm.envString("MAINNET_RPC_URL"));',
    '        } else {',
    '            vm.createSelectFork(vm.envString("MAINNET_RPC_URL"), forkBlock);',
    '        }',
    '',
    '        // §9.1: resolve the Pool through the provider, never hardcode it.',
    '        POOL = IPool(PROVIDER.getPool());',
    '        owner = makeAddr("owner");',
    `        ${INSTANCE} = new ${opts.name}(${ctorArgs.join(', ')});`,
    '    }',
    '',
    '    /// @dev A valid, benign FlashParams. Attack tests deviate from this deliberately.',
    `    function _defaultFlashParams() internal pure returns (${opts.name}.FlashParams memory) {`,
    `        return ${opts.name}.FlashParams({`,
    ...paramFields(opts).map((f, i, a) => `            ${f}${i === a.length - 1 ? '' : ','}`),
    '        });',
    '    }',
    '',
    '    function _defaultParams() internal pure returns (bytes memory) {',
    '        return abi.encode(_defaultFlashParams());',
    '    }',
  );

  for (const [id, snippet] of chosen) {
    lines.push('', ...renderTest(id, snippet, subs));
  }

  for (const snippet of chosen) {
    if (snippet[1].helpers?.length) lines.push('', ...snippet[1].helpers.map((h) => `    ${h}`));
  }

  lines.push('}');

  const source = lines.join('\n');
  const leftover = source.match(/\{\{[A-Z_]+\}\}/g);
  if (leftover) {
    throw new Error(`Unsubstituted placeholder(s) in attack tests: ${[...new Set(leftover)].join(', ')}`);
  }

  return { source, testNames: chosen.map(([, s]) => s.testName), skipped };
}

function paramFields(opts: GenerateOptions): string[] {
  const fields = ['minAmountOut: 1', 'deadline: type(uint256).max'];
  if (opts.routerAllowlist) fields.push('router: address(0)');
  return fields;
}

function renderTest(
  id: FindingId,
  snippet: AttackSnippet,
  subs: Record<string, string>,
): string[] {
  const substitute = (s: string) =>
    Object.entries(subs).reduce((acc, [k, v]) => acc.split(k).join(v), s);

  const out: string[] = [`    /// ${id} — ${snippet.title}`];
  for (const c of snippet.comments ?? []) out.push(`    /// ${substitute(c)}`);
  for (const inc of snippet.incidents) {
    out.push(`    /// @dev Incident: ${inc.name} — ${inc.url}`);
    if (inc.pocFolder) {
      out.push(
        `    /// @dev Runnable PoC: https://github.com/sanbir/evm-hack-registry/tree/main/${inc.pocFolder}`,
      );
    }
  }
  out.push(`    function ${snippet.testName}() public {`);
  for (const line of snippet.body) {
    out.push(line === '' ? '' : `        ${substitute(line)}`);
  }
  out.push('    }');
  return out;
}
